apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
  labels:
    app: postgres
data:
  POSTGRES_DB: bernstein
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: postgres-service
