- name: Install packages required for all servers
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python3
    - python3-pip
    - python3-setuptools
  become: true

- name: Update apt
  apt:
    update_cache: yes
  become: true
