##
## EPITECH PROJECT, 2021
## delivery
## File description:
## Makefile
##

all:
	cd generator && make
	cd solver && make

clean:
	cd generator && make clean
	cd solver && make clean
	cd solver && rm -f solver
	cd generator && rm -f generator

fclean: 	clean

re:	fclean all
