#!/usr/bin/env python3

from math import sqrt, exp, pi
import sys

def print_help():
    print("USAGE")
    print("\t./205IQ u s [IQ1] [IQ2]")
    print("")
    print("DESCRIPTION")
    print("\tu\tmean")
    print("\ts\tstandard deviation")
    print("\tIQ1\tminimum IQ")
    print("\tIQ2\tmaximum IQ")

def gauss(x, u, s):
    return (1 / (sqrt(2 * pi) * s)) * exp(-((x - u) ** 2) / (2 * s ** 2))

def simpson(a, b, u, s):
    n = 10000
    h = (b - a) / n
    res = 0
    for i in range(n):
        res += gauss(a + i * h, u, s) + 4 * gauss(a + i * h + h / 2, u, s) + gauss(a + (i + 1) * h, u, s)
    return res * h / 6

def main():
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        print_help()
        exit(0)
    if len(sys.argv) < 3 or len(sys.argv) > 5:
        print("Invalid number of arguments")
        exit(84)
    try:
        u = float(sys.argv[1])
        s = float(sys.argv[2])
        if s <= 0 or u <= 0 or u > 200: 
            print("Invalid arguments")
            exit(84)
        if len(sys.argv) == 3:
            for i in range(0, 201):
                print("{:.0f} {:.5f}".format(i, gauss(i, u, s)))

        if len(sys.argv) == 4:
            IQ = int(sys.argv[3])

            if IQ > 200:
                print("Invalid arguments")
                exit(84)
            
            if IQ < 0:
                print("Invalid arguments")
                exit(84)

            IQ1 = 0
            simpson1 = simpson(IQ, u, u, s)
            simpson2 = simpson(IQ1, u, u, s)
            print("{:.1f}".format((simpson2 - simpson1) * 100) + "% of people have an IQ inferior to " + str(IQ))
        
        if len(sys.argv) == 5:
            IQ1 = int(sys.argv[3])
            IQ2 = int(sys.argv[4])

            if IQ1 > 200 or IQ2 > 200:
                print("Invalid arguments")
                exit(84)
            
            if IQ1 == IQ2:
                print("Invalid arguments")
                exit(84)

            if IQ1 < 0 or IQ2 < 0:
                print("Invalid arguments")
                exit(84)

            simpson1 = simpson(IQ1, u, u, s)
            simpson2 = simpson(IQ2, u, u, s)
            print("{:.1f}".format((simpson1 - simpson2) * 100) + "% of people have an IQ between " + str(IQ1) + " and " + str(IQ2))

            if IQ1 > IQ2:
                print("Invalid arguments")
                exit(84)
    
    except ValueError:
        print("Invalid arguments")
        exit(84)

if __name__ == "__main__":
    main()